services:
  - type: web
    name: my-nuxt-app
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production